apiVersion: v1
kind: Service
metadata:
  name: dex-mi-staging-metabase-service
  namespace: dex-mi-staging
  labels:
    app: dex-mi-staging-metabase-webapp
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: dex-mi-staging-metabase-webapp
