apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-mi-production-metabase-deployment
  namespace: dex-mi-production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: dex-mi-production-metabase-webapp
  template:
    metadata:
      labels:
        app: dex-mi-production-metabase-webapp
        tier: frontend
    spec:
      containers:
        - name: webapp
          image: metabase/metabase:v0.41.9
          imagePullPolicy: IfNotPresent
          env:
          - name: MB_DB_TYPE
            value: "postgres"
          - name: MB_DB_CONNECTION_URI
            valueFrom:
              secretKeyRef:
                name: dex-mi-production-rds-output
                key: url
          envFrom:
            - configMapRef:
                name: environment-variables
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
          
