# The following line is purely for secret checking purpose no other use, please DO NOT REMOVE IT
#WARNING_Secrets_Are_Not_Encrypted!
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MB_ENCRYPTION_SECRET_KEY: cWQ2aEF4ZnhGOXlHZUJkVXJMVzZ6NDVqNWQzVmZWNDI=
